[all]
jump-node ansible_host={{ BASTION_IP }} ansible_user=ubuntu

[kube_control_plane]
master1 ansible_host=10.0.141.55  # 실제 프라이빗 IP로 수정

[etcd]
master1 ansible_host=10.0.141.55

[kube_node]
worker1 ansible_host=10.0.134.65
worker2 ansible_host=10.0.134.11
worker3 ansible_host=10.0.137.1

[k8s_cluster:children]
kube_control_plane
kube_node